//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod
    {
        public int Id { get; set; }
        public string SKU { get; set; }
        public string brand { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string feature { get; set; }
        public string productParameter { get; set; }
    }
}
